version: '3.9'
services:
  front:
    build:
      context: .
      dockerfile: front/${DOCKERFILE_NAME:-Dockerfile.dev}
    volumes:
      - ./front:/front
      - /front/node_modules
      - /front/next
    environment:
      NEXT_PUBLIC_FRONT_URI: ${FRONT_URI}
      REVALIDATE_TIMEOUT: ${REVALIDATE_TIMEOUT:-60}
    ports:
      - 127.0.0.1:${FRONT_PORT:-3010}:3000
    networks:
      - webappnetwork

networks:
  webappnetwork:
    driver: bridge
